import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Heading } from "@/components/heading";
import { SubHeading } from "@/components/subHeading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Number Guessing Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex min-h-screen flex-col items-center justify-between p-24'>
          <div>
            <Heading text='Number Guessing Game' />
            <SubHeading text='How to Play?' />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
